name: Enviar promoções

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  enviar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install requests

      - name: Enviar promoção
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        run: python bot.py

      - name: Salvar alteração
        run: |
          git config user.name "Bot Promocoes"
          git config user.email "bot@users.noreply.github.com"
          git add promocoes.txt
          git commit -m "Promoção enviada" || exit 0
          git push
